nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.0.2.cjs
npmScopes:
  organization이름(ex. dramancompany):
    npmAlwaysAuth: true
    # NOTE: 로컬에서 설치 시 터미널에 'export NPM_AUTH_TOKEN=...' 명령어로 환경변수를 설정
    npmAuthToken: ${NPM_AUTH_TOKEN} # https://github.com/yarnpkg/berry/pull/1341
    npmRegistryServer: 'https://npm.pkg.github.com'
