name: React build
on:
  push: # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'  
      - name: Enable Corepack
        run: corepack enable

      - name: Install correct Yarn version
        run: corepack prepare yarn@4.0.2 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://over-brain2